security:
    encoders:
        AppBundle\Entity\BlogUser:
            algorithm: bcrypt
            cost: 14
    providers:
        blog_user_db:
            entity:
                class: AppBundle\Entity\BlogUser
                property: username
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
                csrf_token_generator: security.csrf.token_manager
            logout_on_user_change: false
            logout:
                path:   /private/logout
                target: /
            provider: blog_user_db

    access_control:
        # require ROLE_ADMIN for /private*
        - { path: ^/private, roles: ROLE_ADMIN }